# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/universal8895-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter dreamlte dream2lte greatlte,$(TARGET_DEVICE)),)

endif
